services:
  # A Python web service
  - type: web
    name: www
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash ./render.sh
    envVars:
      - key: ADDR
        sync: false
      - key: PASSWORD
        sync: false
      - key: ADMIN
        sync: false
      - key: BOT_NAME
        sync: false
      - key: DELAY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: botkey
          property: connectionString

databases:
  - name: botkey
    plan: free
